# -*- coding: utf-8 -*-
version: 1

root:
  level: INFO
  handlers: [console]

# サブモジュールのロガー設定
loggers:
  llm_server:
    level: DEBUG  
    propagate: false
    handlers: [console]
  llm_server.whisper:
    level: INFO 
    propagate: false
    handlers: [console]

# 書式
formatters:
  dev:
    format: "[%(levelname)-7s] (%(name)-20s) %(message)s"
  full_info:
    format: "%(asctime)s [%(levelname)-7s] (%(name)-20s) %(message)s"
    datefmt: '%Y/%m/%d %I:%M:%S'

# ハンドラ
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: dev
    stream: ext://sys.stdout

disable_existing_loggers: false